### ISSUE TITLE
Add keyboard shortcut to launch the app

### ISSUE THREAD

**Issue by Suzie97** [ryonakano/louper#17]
Right now, the only way to open the app and see the magnified text is to select the text and then open the app using the dock or applications menu.

Providing a keyboard shortcut to launch the app would improve this experience in terms of accessibility and convenience.

**Comment by ryonakano** [comment]
Actually the app register Super+Q to launch the app automatically when it launches for the first time. However, this behavior seems to be not recommended in the Flatpak world, as far as I know. So I removed this behavior in #10.

I really agree your idea and it's reasonable because assigning manually is a little bit bothersome, but unfortunately you need to assign by your self as described in [README](https://github.com/ryonakano/louper#usage).

Closing as "Won't Fix". Thank you for using the app and reporting anyway! ❤️
